### ISSUE TITLE
Compile linux kernel to LLVM IR

### ISSUE THREAD

**Issue by bsauce** [paul-naert/kernel-specialization#1]
Now I am using your tool to compile whole linux kernel to LLVM IR. But I came across some problems. First, in your "built-in-parsing.py", where is the "get-bc" command come from? And I have tried many tools to compile kernel to bitcode, do you have any suggestion? Thanks a lot.

**Comment by bsauce** [comment]
I have installed gllvm. When I run example-build.sh, there is a mistake. Do you know why? Thanks a lot.
```
  SYSTBL  arch/x86/include/generated/asm/syscalls_32.h
  SYSHDR  arch/x86/include/generated/asm/unistd_32_ia32.h
  SYSHDR  arch/x86/include/generated/asm/unistd_64_x32.h
  SYSTBL  arch/x86/include/generated/asm/syscalls_64.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_32.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_x32.h
  HOSTCC  arch/x86/tools/relocs_32.o
  HOSTCC  arch/x86/tools/relocs_64.o
  HOSTCC  arch/x86/tools/relocs_common.o
  HOSTLD  arch/x86/tools/relocs
  UPD     include/config/kernel.release
  WRAP    arch/x86/include/generated/uapi/asm/bpf_perf_event.h
  WRAP    arch/x86/include/generated/uapi/asm/poll.h
  WRAP    arch/x86/include/generated/uapi/asm/socket.h
  WRAP    arch/x86/include/generated/uapi/asm/sockios.h
  WRAP    arch/x86/include/generated/asm/dma-contiguous.h
  WRAP    arch/x86/include/generated/asm/early_ioremap.h
  WRAP    arch/x86/include/generated/asm/export.h
  WRAP    arch/x86/include/generated/asm/mcs_spinlock.h
  WRAP    arch/x86/include/generated/asm/mm-arch-hooks.h
  WRAP    arch/x86/include/generated/asm/mmiowb.h
  UPD     include/generated/uapi/linux/version.h
  UPD     include/generated/utsrelease.h
  HOSTCC  scripts/selinux/genheaders/genheaders
  HOSTCC  scripts/selinux/mdp/mdp
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/pnmtologo
  HOSTCC  scripts/conmakehash
  HOSTCC  scripts/sortextable
  HOSTCC  scripts/asn1_compiler
  HOSTCC  scripts/extract-cert
Compiler lacks asm-goto support.

```

**Comment by ianamason** [comment]
No that's not a problem with `gllvm`, that means the underlying compiler (`clang`) won't be able to compile the kernel.  As I understand it, only certain versions of the kernel will compile with clang.

Not sure why they do not maintain this ability.

My advice to you is to first see if you can get some version of the kernel to compile with 
clang, then try  the gllvm route.

Good luck.  (P.S. I think the https://github.com/SRI-CSL repos are going to be more active as far as responses to queries.).

**Comment by bsauce** [comment]
Now my clang version is 7.0. I will try clang 8.0. If it doesn't succeed, I will compile lower kernel version. Thanks for your suggestion.

**Comment by bsauce** [comment]
For kernel 4.19 and 5.x, clang cannot support "asm goto", so it failed.
